### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by purplecones** [ChrisAlvares/node-adwords#32]
Does the refresh token always have to be refreshed before it expires?

I am trying to refresh a token where the `expiry_date` has passed like so

```javascript
console.log({ refreshToken });
auth.refreshAccessToken(refreshToken, (error, newTokens) => {
  if (error) {
    console.log(error);
  } else {
    console.log(newTokens);
  }
});
```

but get this error 
```
{ refreshToken: '1/RXdGaAPOwhcye1-DNbZJYlz67ArETtPYBRnexxxxxxx' }
Exception while invoking method 'xxx' Error: No refresh token is set.
at OAuth2Client.refreshAccessToken (/xxx/node_modules/google-auth-library/lib/auth/oauth2client.js:199:14)
at AdwordsAuth.refreshAccessToken (/xxx/node_modules/node-adwords/adwords/auth.js:52:27)
```

The `refreshToken` is being passed, not sure why it says that it is not being set. I don't get this issue if I call this method before it `expiry_date`.

**Comment by purplecones** [comment]
Closing issues. Problem was with my code, not related to adwords.
